#!/bin/bash

source /root/spark_files/configure_spark.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "CLIENT_IP=$IP"

echo "preparing Spark"
if [ -z "$MASTER_HOST" ]; then
  echo "Defining MASTER_HOST is mandatory !"
  exit 1
fi

cp /root/spark_client_files/oozie-site.xml /etc/oozie/conf

prepare_spark $MASTER_HOST

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo "configuring oozie"

su - hdfs -c "hadoop fs -mkdir -p /user/oozie"
su - hdfs -c "hadoop fs -chmod 775 /user"
su - hdfs -c "hadoop fs -chown oozie:hadoop /user/oozie"
su - hdfs -c "hadoop fs -ls /user/oozie" | grep -q /user/oozie/share || /usr/bin/oozie-setup sharelib create -fs hdfs://$MASTER_HOST:9000 -locallib /usr/lib/oozie/oozie-sharelib-yarn.tar.gz

echo "starting Spark Client"
cp /root/spark_client_files/run_spark_client.sh /
chmod a+rx /run_spark_client.sh
/run_spark_client.sh
