#!/bin/bash

set -x

echo "starting to configure"

env

source /root/spark_files/configure_spark.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"

echo "preparing Spark"
if [ -z "$MASTER_HOST" ]; then
  echo "Defining MASTER_HOST is mandatory !"
  exit 1
fi

prepare_spark $MASTER_HOST

echo "starting Hadoop Master services"
su - hdfs -c "/usr/bin/hdfs namenode -format"
service hadoop-hdfs-namenode start 

su - hdfs -c "hadoop fs -chown hdfs:hadoop /"
su - hdfs -c "hadoop fs -chmod 775 /"
su - hdfs -c "hadoop fs -mkdir /tmp"
su - hdfs -c "hadoop fs -chown mapred:hadoop /tmp"

service hadoop-yarn-resourcemanager start 
service hadoop-mapreduce-historyserver start 
service zookeeper-server start

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo "starting Spark Master"
cp /root/spark_master_files/run_spark_master.sh /
chmod a+rx /run_spark_master.sh
/run_spark_master.sh
