#!/bin/bash

source /root/hadoop_files/configure_hadoop.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "WORKER_IP=$IP"

echo "preparing Hadoop"
if [ -z "$MASTER_HOST" ]; then
  echo "Defining MASTER_HOST is mandatory !"
  exit 1
fi

prepare_hadoop $MASTER_HOST

echo "starting Hadoop Worker services"
service hadoop-hdfs-datanode start
service hadoop-yarn-nodemanager start

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo "starting Hadoop Worker"
cp /root/hadoop_worker_files/run_hadoop_worker.sh /
chmod a+rx /run_hadoop_worker.sh
/run_hadoop_worker.sh
